version = 1

[[annotations]]
path = ["include/*", "tests/*", "examples/*", "CMakeLists.txt"]
SPDX-FileCopyrightText = ["(C) 2025 Marco Celoria <celoria.marco@gmail.com>"]
SPDX-License-Identifier = "AGPL-3.0-or-later"


